---
# Install docker registry
- hosts: registry
  become: true
  roles:
    - dockerce.install
    - role: dockerce.registry
      dockerRegistryPort: "{{_registryPort }}"
      dockerRegistrySslKey: "{{_registrySSLKey}}"
      dockerRegistrySslCertificate: "{{_registrySSLCertificate}}"
