---
# Install docker service
- hosts: node
  become: true

  roles:
    - role: dockerce.install
      dockerClientCACertificat: "{{_clientCACertificate}}"
      dockerClientPrivateKey: "{{_clientPrivateKey}}"
      dockerTrustRegistry:
        domain: "{{groups.registry[0]}}"
        certificate: "{{_registrySSLCertificate}}"
      when: _registryPort == 443
    - role: dockerce.install
      dockerTrustRegistry:
        domain: "{{groups.registry[0]}}:{{_registryPort}}"
        certificate: "{{_registrySSLCertificate}}"
      when: _registryPort != 443
